--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/VennDev/VDoPlayer
build-by-default: true
branches:
- main
projects:
  VDoPlayer:
    path: ""
    model: virion
    type: library
...
